name: alfred_gitmoji
description: Search for gitmojis and copy them to the clipboard easily.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.3.5

environment:
  sdk: ^3.9.0


dependencies:
  algoliasearch: ^1.41.1
  args: ^2.7.0
  alfred_workflow: ^1.2.0
  cli_script: ^1.0.0
  crypto: ^3.0.6
  envied: ^1.3.1
  http: ^1.5.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  recase: ^4.1.0
  stash: ^5.2.0

dev_dependencies:
  build_runner: ^2.10.1
  envied_generator: ^1.3.1
  json_serializable: ^6.11.1
  lints: ^6.0.0
